generate:
	buf generate
	buf generate --template '{"version":"v1","plugins":[{"name":"openapiv2","out":"../web/dist/swagger-ui/", "opt": [ "allow_repeated_fields_in_body=true"]}]}' question/v1alpha1/service.proto
